# Generated by Django 5.2.8 on 2026-04-10 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('field_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('access_level', models.CharField(choices=[('read', 'Read Access'), ('edit', 'Edit Access')], max_length=50)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Permission',
                'verbose_name_plural': 'Field Permissions',
                'constraints': [models.UniqueConstraint(fields=('model_name', 'field_name', 'access_level'), name='unique_model_field_access')],
            },
        ),
    ]
